base_lr: 0.1
batch_size: 4
checkpoint_path: checkpoints/NEW_60_10FPS
gpus: 1
log_dir: logs/NEW_60_10FPS
num_classes: 60
num_epochs: 30
save_freq: 5
steps:
- 10
- 40
test_data_path: data/ntu/xsub/val_data
train_data_path: data/ntu/xsub/train_data
